import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import Card from "../components/UI/Card";
import Filter from "../components/FilterItems/Filters";
import SerchResult from "../components/Results/SerchResult";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card>
      <div className="p-2 bg-secondary-subtle rounded-3 h-100 overflow-auto ">
        <Filter />
      </div>
      <div className="p-2 h-100 w-100 text-center overflow-auto">
        <SerchResult />
      </div>
    </Card>
    </>
  )
}
